layout_spectrum: 0.9418213
favicon: null
name: Alphamay
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.8372681
  lightness: 0.6408094
  saturation: 0.6096122
  rhythmicContrast: 0.4005059
  brandColors:
    - '#F1F0F1'
    - '#282727'
    - '#9B999B'
    - '#F29CB4'
    - '#87292E'
typography_spectrum: 0.5548061
